version: '3.8'
services:
  mongodb:
    image: mongo
    volumes:
      - mongodata:/data/db
      - ./dump/:/dump/
    ports:
      - 127.0.0.1:27017:27017
    restart: unless-stopped  
    
volumes:
      mongodata:
